default: &default
  adapter: postgresql
  encoding: unicode
  # for docker container: db
  host: <%= ENV['DEV_DB_HOST'] %>
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: blank_dev

test:
  <<: *default
  database: blank_test

production:
  <<: *default
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: blank_production